<script setup>
/**
 * Saved builds - setups generated by the quiz and kept against your account.
 *
 * The route guard means we only get here signed in, so there is no signed-out
 * state to render.
 */

import { ref, onMounted } from 'vue'
import { listBuilds, deleteBuild } from '../services/api.js'
import BuildSummary from '../components/BuildSummary.vue'
import LoadingState from '../components/LoadingState.vue'
import ErrorMessage from '../components/ErrorMessage.vue'

const builds = ref([])
const loading = ref(true)
const error = ref('')

async function load() {
  loading.value = true
  error.value = ''

  try {
    builds.value = await listBuilds()
  } catch (err) {
    error.value = err.message
  } finally {
    loading.value = false
  }
}

async function remove(build) {
  if (!confirm(`Delete "${build.build_name}"? This cannot be undone.`)) return

  const previous = builds.value
  // Drop it from the list straight away, and put it back if the server says no.
  builds.value = builds.value.filter((b) => b.id !== build.id)

  try {
    await deleteBuild(build.id)
  } catch (err) {
    builds.value = previous
    error.value = err.message
  }
}

onMounted(load)
</script>

<template>
  <div class="builds section container">
    <div class="section-head">
      <span class="eyebrow">Saved builds</span>
      <h1>Your builds</h1>
      <p>
        Setups the quiz generated for you. Each one keeps the parts, the scores and the
        upgrade path exactly as they were when you saved it.
      </p>
    </div>

    <LoadingState v-if="loading" message="Loading your builds..." />

    <ErrorMessage v-else-if="error" :message="error" retryable @retry="load" />

    <div v-else-if="!builds.length" class="card empty">
      <h2>Nothing saved yet</h2>
      <p class="muted">
        Run the quiz, generate a setup, and hit Save Build. It will show up here.
      </p>
      <RouterLink to="/quiz" class="btn btn-lg">Start Setup Quiz</RouterLink>
    </div>

    <div v-else class="grid grid-2">
      <BuildSummary v-for="build in builds" :key="build.id" :build="build" @delete="remove" />
    </div>
  </div>
</template>

<style scoped>
.empty {
  text-align: center;
  padding: var(--space-7);
}

.empty p {
  margin: var(--space-3) auto var(--space-5);
  max-width: 44ch;
}
</style>
